# Copyright 2013 6WIND S.A.

FASTPATH_PLUGIN=y
include $(DIST_FP)/fp-plugins/common/mk/plugin-init.mk

VPATH= $(S)

LIB= fp_if_output.so
SHARED_LIB=yes

SRCS= fp_if_output.c

include $(DIST_FP)/fp-plugins/common/mk/plugin-lib.mk
