# Copyright 2013 6WIND S.A.

MODULE        = blade-ipsec
MODULE_PATH   = net
SRCS          = blade-ipsec.c

MODULE_CFLAGS += -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
MODULE_CFLAGS += -Wno-error=type-limits
MODULE_CFLAGS += -Wno-error=old-style-declaration
MODULE_CFLAGS += -std=gnu89

MODULE_CFLAGS += -I$(S)/../common
MODULE_CFLAGS += -I$(S)

override EXTRA_CFLAGS := $(MODULE_CFLAGS)

obj-m          += $(MODULE).o
ifneq ($(MODULE),$(patsubst %.S,%,$(SRCS:%.c=%)))
$(MODULE)-objs += $(patsubst %.S,%.o,$(SRCS:%.c=%.o))
endif
