# Copyright 2013-2014 6WIND S.A.

include $(DIST_FP)/fp-plugins/common/mk/plugin-init.mk

VPATH= $(S)
CFLAGS += -I$(S)/..

PROG= pppoe-predict-dest

CFLAGS += -Wno-unused

SRCS= pppoe-predict-dest.c

include $(FPNSDK_DIR)/mk/prog.mk
