# Copyright 2013 6WIND S.A.

FASTPATH_PLUGIN=y
include $(DIST_FP)/fp-plugins/common/mk/plugin-init.mk

VPATH= $(S)

LIB= fp_ether_input.so
SHARED_LIB=yes

SRCS= fp_ether_input.c

include $(DIST_FP)/fp-plugins/common/mk/plugin-lib.mk
