# Copyright 2013 6WIND S.A.

MODULE        = blade-neigh
MODULE_PATH   = net
SRCS          = blade-neigh.c

EXTRA_CFLAGS += -Wall -Werror
EXTRA_CFLAGS += -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
EXTRA_CFLAGS += -Wno-error=type-limits
EXTRA_CFLAGS += -Wno-error=old-style-declaration
EXTRA_CFLAGS += -std=gnu89

EXTRA_CFLAGS += -I$(S)

obj-m          += $(MODULE).o
ifneq ($(MODULE),$(patsubst %.S,%,$(SRCS:%.c=%)))
$(MODULE)-objs += $(patsubst %.S,%.o,$(SRCS:%.c=%.o))
endif
