softid
   A user defined id that should be set in Flow Director hash in matching
   packets.
flex_bytes
   Flex bytes value to match.
vlan_id
   VLAN ID value to match.
iptype
   IP packet type to match: ipv4 or ipv6 (defaults to ipv4).
ip_src
   IPv4/IPv6 source address to match (depends on iptype).
ip_dst
   IPv4/IPv6 destination address to match (depends on iptype).
l4type
   L4 protocol to match: none, udp, tcp or sctp.
port_src
   L4 source port to match.
port_dst
   L4 destination port to match.

