# Copyright 2014 6WIND S.A.

PROG = igbuio_modalias

VPATH = $(S)

SRCS = igbuio_modalias.c

CFLAGS := -Wall -Werror
CFLAGS += -I$(RTE_SDK)/$(RTE_TARGET)/include
LDFLAGS :=
LDLIBS :=

include mk/prog.mk
