# Copyright 2013 6WIND S.A.

MODULE        = ifuid
MODULE_PATH   = net
SRCS          = ifuid.c

EXTRA_CFLAGS += -Wall -Werror
EXTRA_CFLAGS += -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers
EXTRA_CFLAGS += -Wno-error=type-limits
EXTRA_CFLAGS += -Wno-error=old-style-declaration
EXTRA_CFLAGS += -std=gnu89

EXTRA_CFLAGS += -I$(S)

IFUID_DIR?=/usr/local/modules/ifuid
DIST_IFUID?=$(IFUID_DIR)
EXTRA_CFLAGS += -I$(DIST_IFUID)/ifuid-module/

ifeq ($(USE_VRF_NETNS),y)
VRF_DIR?=/usr/local/modules/vrf
DIST_VRF?=$(VRF_DIR)
EXTRA_CFLAGS += -I$(DIST_VRF)/vrf-module/
EXTRA_CFLAGS += -DUSE_VRF_NETNS
# Using symbol vrf_lookup_by_net
VRF_BINDIR?=$(VRF_DIR)
ifeq ($(wildcard $(VRF_BINDIR)/vrf-module/$(KERNELRELEASE)/$(KERNELARCH)/Module.symvers),)
KBUILD_EXTRA_SYMBOLS += $(VRF_BINDIR)/vrf-module/Module.symvers
else
KBUILD_EXTRA_SYMBOLS += $(VRF_BINDIR)/vrf-module/$(KERNELRELEASE)/$(KERNELARCH)/Module.symvers
endif
endif

obj-m          += $(MODULE).o
ifneq ($(MODULE),$(patsubst %.S,%,$(SRCS:%.c=%)))
$(MODULE)-objs += $(patsubst %.S,%.o,$(SRCS:%.c=%.o))
endif
