# Copyright 2013 6WIND S.A.

FASTPATH_PLUGIN=y
include $(DIST_FP)/fp-plugins/common/mk/plugin-init.mk

VPATH= $(S)

LIB= rr-load-balancer.so
SHARED_LIB=yes

SRCS= rr-load-balancer.c

include $(DIST_FP)/fp-plugins/common/mk/plugin-lib.mk
