VPATH= $(S)

LIB= libnetfpc.a

SHARED_LIB=no

SRCS= netfpc.c

CFLAGS += -Wall -Wextra -Werror
CFLAGS += -Wundef
CFLAGS += -Wno-unused-parameter -Wstrict-prototypes
CFLAGS += -std=gnu99

include $(FPNSDK_DIR)/mk/lib.mk
